# launch everything: docker compose up --build -d

services:
  app:
    build: .
    container_name: go_web_server
    ports:
      - "5080:5080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: my_db

  db:
    image: postgres:16
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"



